src/adapters/app/blueprints/auth.py
import functools

from flask import Blueprint, request, redirect, render_template, url_for, flash, session, g
from src.domain.ports.user_service import UserService, UserDBOperationError
from dependency_injector.wiring import inject, Provide
from src.main.containers import Container
from src.domain.ports import register_user_factory
from werkzeug.security import check_password_hash



blueprint = Blueprint('auth', __name__, url_prefix='/auth')

def login_required(view):
    """View decorator that redirects anonymous users to the login page."""

    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))

        return view(**kwargs)

    return wrapped_view


@blueprint.before_app_request
@inject
def load_logged_in_user(user_service: UserService = Provide[Container.user_package.user_service]):
    """If a user id is stored in the session, load the user object from
    the database into ``g.user``."""
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = (
            user_service.get_user_by_id(user_id)
        )


@blueprint.route('/register', methods=('GET', 'POST'))
@inject
def register(user_service: UserService = Provide[Container.user_package.user_service]):
  if request.method == 'POST':
    user_name = request.form['username']
    password = request.form['password']
    error = None
    if not user_name:
        error = 'Username is required.'
    elif not password:
        error = 'Password is required.'

    user_ = register_user_factory(user_name=user_name, password=password)
    if user_:
      try:
        user_service.create(user_)
      except UserDBOperationError as err:
        print(err)
        error = f"Something went wrong with database operation {err}"
      else:
        return redirect(url_for("auth.login"))
    flash(error)

  return render_template('auth/register.html')


@blueprint.route('/login', methods=('GET', 'POST'))
@inject
def login(user_service: UserService = Provide[Container.user_package.user_service]):
    if request.method == 'POST':
      user_name = request.form['username']
      password = request.form['password']

      error = None
      user = user_service.get_user_for_login(user_name=user_name)
      if not user:
          error = 'Incorrect username.'
      elif not check_password_hash(user.password, password):
          error = 'Incorrect password.'

      if not error:
          session.clear()
          session['user_id'] = user.id
          return redirect(url_for('index'))

      flash(error)

    return render_template('auth/login.html')


@blueprint.route("/logout")
def logout():
    """Clear the current session, including the stored user id."""
    session.clear()
    return redirect(url_for("index"))

src/adapters/app/blueprints/blog.py
from flask import Blueprint, render_template, request, flash, g, redirect, url_for
from dependency_injector.wiring import inject, Provide
from src.adapters.app.blueprints.auth import login_required
from src.domain.ports.post_service import PostService, BlogDBOperationError
from src.domain.ports import create_post_factory, update_post_factory, delete_post_factory
from src.main.containers import Container

blueprint = Blueprint('post', __name__)


@blueprint.route('/')
@inject
def index(post_service: PostService = Provide[Container.blog_package.post_service]):
    posts = post_service.get_all_blogs()
    return render_template('post/index.html', posts=posts)


@blueprint.route('/create', methods=('GET', 'POST'))
@login_required
@inject
def create(post_service: PostService = Provide[Container.blog_package.post_service]):
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        post = create_post_factory(author_id=g.user.id, title=title, body=body)
        if not error:
            try:
                post_service.create(post)
            except BlogDBOperationError as err:
                error = f"Something went wrong with database operation {err}"
            else:
                return redirect(url_for('post.index'))
        flash(error)

    return render_template('post/create.html')



@blueprint.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
@inject
def update(id, post_service: PostService = Provide[Container.blog_package.post_service]):
    post = post_service.get_post_by_id(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        _post = update_post_factory(id=id, title=title, body=body)

        if not error:
            try:
                post_service.update(_post)
            except BlogDBOperationError as err:
                error = f"Something went wrong with database operation {err}"
            else:
                return redirect(url_for('post.index'))
        flash(error)

    return render_template('post/update.html', post=post)


@blueprint.route('/<int:id>/delete', methods=('POST',))
@login_required
@inject
def delete(id, post_service: PostService = Provide[Container.blog_package.post_service]):
    post_service.get_post_by_id(id)
    _post = delete_post_factory(id=id)
    try:
        post_service.delete(_post)
    except BlogDBOperationError as err:
        error = f"Something went wrong with database operation {err}"
    else:
        return redirect(url_for('post.index'))
    flash(error)

src/adapters/app/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1><a href="{{ url_for('index') }}">Flaskr</a></h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

src/adapters/app/templates/post/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

src/adapters/app/templates/post/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Posts{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('post.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post['title'] }}</h1>
          <div class="about">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action" href="{{ url_for('post.update', id=post['id']) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ post['body'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

src/adapters/app/templates/post/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('post.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}